# Harder Spawners Configuration.
# Debug settings
debugLevel=0 # int | default: 0 | possible values: 0-2; 0 off, 1 some detail, 2 high detail.
spawnerTextOff=1 # int | default: 1 | possible values: 0=show text, 1=hide text
# 
# Spawner behavior settings
spawnerMinutesStunned=0 # int | default: 0 | possible values: 0=Spawner Breaks, 1 to 27 = minutes Spawner stunned
spawnerBreakSpeedModifier=1 # int | default: 1 | possible values: Slows mining of Spawners.  -1=Feature off. 0-3 = mining fatigue 1-4
spawnerRevengeLevel=1 # int | default: 1 | possible values: Range 0-11.  0=Off.  1 to 11 increases relation power
spawnersExplodePercentage=33 # int | default: 33 | possible values: 0 = 0ff.  0-100% chance of explosions.
# 
# Environmental settings
destroyLightPercentage=100 # int | default: 100 | possible values: 0-100% chance to destroy light emitting blocks.
destroyLightRange=7 # int | default: 7 | possible values: 1 to 9 block range from spawner
hostileSpawnerLightLevel=11 # int | default: 11 | possible values: 0-15; allows spawning in higher light levels.
hostileSpawnerResistDaylightDuration=120 # int | default: 120 | possible values: 0 to 2 billion Seconds of fire resist for undead mobs spawned by this spawner.
# 
# Spawning mechanics
requiredPlayerRange=13 # int | default: 13 | possible values: When players are within this range (6 to 24) the spawner starts spawning.
maxNearbyEntities=9 # int | default: 9 | possible values: 6 to 15 maximum number of mobs nearby before spawn blocked
spawnRange=9 # int | default: 9 | possible values: 6 to 32 Mobs spawn within 0 to value blocks from spawner.
# 
# Spawn delay overrides
preserveNonVanillaSpawnerTiming=true # boolean | default: true | possible values: true/false; keep vanilla spawner timing
minSpawnDelayOverride=200 # int | default: 200 | possible values: 60 to 600 ticks; min spawn delay
maxSpawnDelayOverride=800 # int | default: 800 | possible values: 600 to 6000 ticks; max spawn delay
# Note max must be > min or it resets to max = min + 100
# 
# Lifespan
addLifespanItem=minecraft:iron_block # String | default: minecraft:iron_block | possible values: item id; block or item consumed to increase spawner lifespan. 
extraLifespanAmount=5 # int | default: 5 | possible values: 0 to 320,000 ticks added to spawner lifespan
# List of default, and mobs default (min to max) number of spawns.
mobSpawnerDurabilityRangesString=harderspawners:default,200,600;minecraft:pig,0,0;minecraft:cow,0,0;minecraft:sheep,0,0;minecraft:parrot,0,0;minecraft:zombie,100,550;minecraft:blaze,0,0; # String | default: harderspawners:default,200,600;minecraft:pig,0,0;minecraft:cow,0,0;minecraft:sheep,0,0;minecraft:parrot,0,0;minecraft:zombie,100,550;minecraft:blaze,0,0; | possible values: format: modid:name,min,max; ...
# DESTROYED: Spawner breaks or explodes.
# LINGER: does not break but only spawns every 25 minutes until repaired.
endOfLifespanAction=DESTROYED # String | default: DESTROYED | possible values: DESTROYED/LINGER; action at end of lifespan
# End of Harder Spawners Configuration.

