#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Mar 12 14:24:26 IST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=Bliss_v2.1.2_(Chocapic13_Shaders_edit).zip
